doctrine:
    dbal:
        default_connection: default
        connections:
            test:
                dbname: 'thevillage_test'
                user: 'root'
                password: ''
                host: '127.0.0.1'
                driver: 'pdo_mysql'
                server_version: '7.4.8'
            default:
                dbname: 'thevillage'
                user: 'root'
                password: ''
                host: '127.0.0.1'
                driver: 'pdo_mysql'
                server_version: '7.4.8'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
